#!/usr/bin/env python3
# _*_ coding: utf8 _*_
"""
app.py

Author: Gris Iscomeback
Email: grisun0[at]proton[dot]me
Creation Date: 06/18/2026
License: GPL v3

Description: MCP server to monitor AFL++ fuzzing sessions and execute FreeDom in headless mode.
"""

import os
import subprocess
import logging
import sys
from mcp.server.fastmcp import FastMCP

# Force all logging to use stderr, keeping stdout clean for JSON-RPC transport
logging.basicConfig(
    level=logging.INFO,
    stream=sys.stderr,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)

app = FastMCP("Freedom-Fuzz-Monitor")

@app.tool()
def read_fuzz_stats() -> str:
    """Reads the current status of the active AFL++ fuzzing session."""
    stats_path = "fuzz/out/default/fuzzer_stats"
    if not os.path.exists(stats_path):
        return "The fuzzing session has not generated statistics yet."
    with open(stats_path, "r") as f:
        return f.read()

@app.tool()
def list_unique_crashes() -> list:
    """Lists all unique crash files generated by the fuzzer that broke the browser."""
    crash_dir = "fuzz/out/default/crashes"
    if not os.path.exists(crash_dir):
        return []
    return [f for f in os.listdir(crash_dir) if f != "README.txt"]

@app.tool()
def run_freedom_headless(payload_path: str) -> str:
    """Executes the FreeDom browser in headless mode against a specific file input or mutated seed.
    
    Args:
        payload_path: The relative or absolute path to the HTML/JS file to process (e.g., 'fuzz/in/seed.html').
    """
    binary_path = "./build/freedom"
    
    if not os.path.exists(binary_path):
        return f"Error: Target binary not found at {binary_path}. Please compile the project first."
        
    if not os.path.exists(payload_path):
        return f"Error: Target payload file not found at {payload_path}."

    try:
        # Run the target browser standalone in headless mode
        result = subprocess.run(
            [binary_path, "--headless", payload_path],
            capture_output=True,
            text=True,
            timeout=5 # Prevent the agent from hanging if a bad loop occurs
        )
        
        output = []
        if result.stdout:
            output.append(f"--- stdout ---\n{result.stdout}")
        if result.stderr:
            output.append(f"--- stderr ---\n{result.stderr}")
            
        return "\n".join(output) if output else "Execution finished with no output logs."

    except subprocess.TimeoutExpired:
        return "Error: Execution timed out (process took longer than 5 seconds)."
    except Exception as e:
        return f"Error executing headless browser: {str(e)}"

if __name__ == "__main__":
    app.run(transport="stdio")