/*
 * TDD suite for image_decode — PNG decode to premultiplied ARGB32.
 *
 * Deterministic: no I/O. Decode runs against an embedded, known PNG fixture so the
 * pixel checks are exact. Build: make test   ;   ASan: make asan
 */

#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <setjmp.h>
#include <string.h>
#include <cmocka.h>

#include "image_decode.h"

/* A 2x2 RGBA PNG generated by zlib/struct (see commit notes). Pixels, document
 * order (row 0 then row 1), non-premultiplied as PNG stores them:
 *   (0,0) red   opaque   255,0,0,255
 *   (1,0) green opaque   0,255,0,255
 *   (0,1) blue  opaque   0,0,255,255
 *   (1,1) white alpha128 255,255,255,128
 * After decode to premultiplied ARGB32 (0xAARRGGBB) the expected pixels are:
 *   (0,0)=0xFFFF0000 (1,0)=0xFF00FF00 (0,1)=0xFF0000FF (1,1)=0x80808080. */
static const uint8_t PNG_2x2[] = {
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
    0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x02,
    0x08, 0x06, 0x00, 0x00, 0x00, 0x72, 0xb6, 0x0d, 0x24, 0x00, 0x00, 0x00,
    0x13, 0x49, 0x44, 0x41, 0x54, 0x78, 0xda, 0x63, 0xf8, 0xcf, 0xc0, 0xf0,
    0x1f, 0x0c, 0x81, 0x34, 0x08, 0x34, 0x00, 0x00, 0x49, 0x49, 0x09, 0x78,
    0x9c, 0x51, 0x17, 0x92, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44,
    0xae, 0x42, 0x60, 0x82
};

static uint32_t px(const img_pixels *p, uint32_t x, uint32_t y) {
    const uint8_t *row = p->data + (size_t)y * p->stride;
    const uint8_t *q = row + (size_t)x * 4u;
    /* Little-endian ARGB32: bytes B,G,R,A -> 0xAARRGGBB. */
    return (uint32_t)q[0] | ((uint32_t)q[1] << 8)
         | ((uint32_t)q[2] << 16) | ((uint32_t)q[3] << 24);
}

/* --- img_sniff --- */

static void test_sniff_png(void **state) {
    (void)state;
    assert_int_equal(img_sniff(PNG_2x2, sizeof PNG_2x2), IMG_FMT_PNG);
}

static void test_sniff_non_png(void **state) {
    (void)state;
    const uint8_t jpeg[] = { 0xff, 0xd8, 0xff, 0xe0, 0, 0, 0, 0 };
    assert_int_equal(img_sniff(jpeg, sizeof jpeg), IMG_FMT_UNKNOWN);
    assert_int_equal(img_sniff(NULL, 0), IMG_FMT_UNKNOWN);
    assert_int_equal(img_sniff(PNG_2x2, 4), IMG_FMT_UNKNOWN); /* too short for the magic */
}

/* --- img_png_dimensions --- */

static void test_dimensions_from_ihdr(void **state) {
    (void)state;
    uint32_t w = 0, h = 0;
    assert_int_equal(img_png_dimensions(PNG_2x2, sizeof PNG_2x2, &w, &h), IMG_OK);
    assert_int_equal(w, 2);
    assert_int_equal(h, 2);
}

static void test_dimensions_truncated(void **state) {
    (void)state;
    uint32_t w = 0, h = 0;
    /* Has the magic but the IHDR is cut off. */
    assert_int_equal(img_png_dimensions(PNG_2x2, 18, &w, &h), IMG_ERR_TRUNCATED);
}

static void test_dimensions_non_png(void **state) {
    (void)state;
    uint32_t w = 0, h = 0;
    const uint8_t junk[16] = {0};
    assert_int_equal(img_png_dimensions(junk, sizeof junk, &w, &h), IMG_ERR_FORMAT);
}

static void test_dimensions_null(void **state) {
    (void)state;
    uint32_t w = 0;
    assert_int_equal(img_png_dimensions(NULL, 0, &w, &w), IMG_ERR_NULL_ARG);
    assert_int_equal(img_png_dimensions(PNG_2x2, sizeof PNG_2x2, NULL, &w), IMG_ERR_NULL_ARG);
}

/* --- img_dimensions_ok (anti-DoS) --- */

static void test_dimensions_ok_bounds(void **state) {
    (void)state;
    assert_int_equal(img_dimensions_ok(1, 1), 1);
    assert_int_equal(img_dimensions_ok(IMG_MAX_DIM, 1), 1);
    assert_int_equal(img_dimensions_ok(0, 1), 0);          /* zero area */
    assert_int_equal(img_dimensions_ok(1, 0), 0);
    assert_int_equal(img_dimensions_ok(IMG_MAX_DIM + 1, 1), 0); /* side cap */
    assert_int_equal(img_dimensions_ok(1, IMG_MAX_DIM + 1), 0);
    /* Within per-side cap but over the area cap. */
    assert_int_equal(img_dimensions_ok(IMG_MAX_DIM, IMG_MAX_DIM), 0);
    /* A pathological pair that would overflow width*height. */
    assert_int_equal(img_dimensions_ok(0xFFFFFFFFu, 0xFFFFFFFFu), 0);
}

/* --- img_fit (aspect-preserving) --- */

static void test_fit_landscape_into_square(void **state) {
    (void)state;
    double w = 0, h = 0;
    /* 200x100 into a 100x100 box -> width-bound: 100x50. */
    img_fit(200, 100, 100.0, 100.0, &w, &h);
    assert_true(w > 99.9 && w < 100.1);
    assert_true(h > 49.9 && h < 50.1);
}

static void test_fit_portrait_into_box(void **state) {
    (void)state;
    double w = 0, h = 0;
    /* 100x200 into a 100x100 box -> height-bound: 50x100. */
    img_fit(100, 200, 100.0, 100.0, &w, &h);
    assert_true(w > 49.9 && w < 50.1);
    assert_true(h > 99.9 && h < 100.1);
}

static void test_fit_degenerate(void **state) {
    (void)state;
    double w = 1, h = 1;
    img_fit(0, 10, 100.0, 100.0, &w, &h);
    assert_true(w == 0.0 && h == 0.0);
    w = 1; h = 1;
    img_fit(10, 10, 0.0, 100.0, &w, &h);
    assert_true(w == 0.0 && h == 0.0);
}

/* --- img_decode_png --- */

static void test_decode_dimensions_and_stride(void **state) {
    (void)state;
    img_pixels p;
    memset(&p, 0, sizeof p);
    assert_int_equal(img_decode_png(PNG_2x2, sizeof PNG_2x2, &p), IMG_OK);
    assert_int_equal(p.width, 2);
    assert_int_equal(p.height, 2);
    assert_int_equal(p.stride, 2u * 4u);
    assert_non_null(p.data);
    img_pixels_free(&p);
}

static void test_decode_pixels_premultiplied(void **state) {
    (void)state;
    img_pixels p;
    memset(&p, 0, sizeof p);
    assert_int_equal(img_decode_png(PNG_2x2, sizeof PNG_2x2, &p), IMG_OK);
    assert_int_equal(px(&p, 0, 0), 0xFFFF0000u); /* red opaque */
    assert_int_equal(px(&p, 1, 0), 0xFF00FF00u); /* green opaque */
    assert_int_equal(px(&p, 0, 1), 0xFF0000FFu); /* blue opaque */
    assert_int_equal(px(&p, 1, 1), 0x80808080u); /* white, alpha 128, premultiplied */
    img_pixels_free(&p);
}

static void test_decode_rejects_non_png(void **state) {
    (void)state;
    img_pixels p;
    memset(&p, 0xAB, sizeof p);
    const uint8_t junk[32] = {0};
    assert_int_equal(img_decode_png(junk, sizeof junk, &p), IMG_ERR_FORMAT);
    assert_null(p.data);
    assert_int_equal(p.width, 0);
}

static void test_decode_rejects_truncated(void **state) {
    (void)state;
    img_pixels p;
    memset(&p, 0, sizeof p);
    /* Valid magic + IHDR but the IDAT is cut, so libpng must fail mid-stream. */
    assert_int_equal(img_decode_png(PNG_2x2, 40, &p), IMG_ERR_DECODE);
    assert_null(p.data);
    img_pixels_free(&p); /* idempotent on a zeroed/failed struct */
}

static void test_decode_null_args(void **state) {
    (void)state;
    img_pixels p;
    memset(&p, 0, sizeof p);
    assert_int_equal(img_decode_png(NULL, 0, &p), IMG_ERR_NULL_ARG);
    assert_int_equal(img_decode_png(PNG_2x2, sizeof PNG_2x2, NULL), IMG_ERR_NULL_ARG);
}

static void test_pixels_free_idempotent(void **state) {
    (void)state;
    img_pixels p;
    memset(&p, 0, sizeof p);
    img_pixels_free(&p);
    img_pixels_free(&p);
    img_pixels_free(NULL);
}

static void test_format_name(void **state) {
    (void)state;
    assert_string_equal(img_format_name(IMG_FMT_PNG), "png");
    assert_string_equal(img_format_name(IMG_FMT_UNKNOWN), "unknown");
}

int main(void) {
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(test_sniff_png),
        cmocka_unit_test(test_sniff_non_png),
        cmocka_unit_test(test_dimensions_from_ihdr),
        cmocka_unit_test(test_dimensions_truncated),
        cmocka_unit_test(test_dimensions_non_png),
        cmocka_unit_test(test_dimensions_null),
        cmocka_unit_test(test_dimensions_ok_bounds),
        cmocka_unit_test(test_fit_landscape_into_square),
        cmocka_unit_test(test_fit_portrait_into_box),
        cmocka_unit_test(test_fit_degenerate),
        cmocka_unit_test(test_decode_dimensions_and_stride),
        cmocka_unit_test(test_decode_pixels_premultiplied),
        cmocka_unit_test(test_decode_rejects_non_png),
        cmocka_unit_test(test_decode_rejects_truncated),
        cmocka_unit_test(test_decode_null_args),
        cmocka_unit_test(test_pixels_free_idempotent),
        cmocka_unit_test(test_format_name),
    };
    return cmocka_run_group_tests(tests, NULL, NULL);
}
