/*
 * gen_psl — build-time generator: turns the vendored Public Suffix List
 * (third_party/psl/public_suffix_list.dat) into a C source file with three
 * sorted, deduplicated, read-only string tables (normal rules, wildcard
 * parents, exceptions). This keeps the runtime lookup pure and in-memory and
 * avoids linking libpsl. Not part of the shipped browser; a build tool.
 *
 * Usage: gen_psl <public_suffix_list.dat> > psl_data.c
 *
 * Both the ICANN and PRIVATE sections are included: for privacy, treating e.g.
 * each "*.github.io" subdomain as its own registrable site is the correct,
 * stricter behaviour.
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct vec {
    char  **items;
    size_t  len;
    size_t  cap;
} vec;

static void vec_push(vec *v, const char *s) {
    if (v->len == v->cap) {
        v->cap = v->cap ? v->cap * 2 : 1024;
        v->items = (char **)realloc(v->items, v->cap * sizeof *v->items);
        if (v->items == NULL) { fputs("oom\n", stderr); exit(1); }
    }
    v->items[v->len] = strdup(s);
    if (v->items[v->len] == NULL) { fputs("oom\n", stderr); exit(1); }
    v->len++;
}

static int cmp_str(const void *a, const void *b) {
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

/* Sorts then drops adjacent duplicates in place. */
static void sort_unique(vec *v) {
    qsort(v->items, v->len, sizeof *v->items, cmp_str);
    size_t w = 0;
    for (size_t i = 0; i < v->len; ++i) {
        if (w == 0 || strcmp(v->items[w - 1], v->items[i]) != 0) {
            v->items[w++] = v->items[i];
        }
    }
    v->len = w;
}

/* ASCII-lowercases in place; UTF-8 high bytes are left untouched. */
static void ascii_lower(char *s) {
    for (; *s; ++s) {
        if (*s >= 'A' && *s <= 'Z') *s = (char)(*s + ('a' - 'A'));
    }
}

static void emit(const char *name, vec *v) {
    printf("const char *const %s[] = {\n", name);
    for (size_t i = 0; i < v->len; ++i) printf("    \"%s\",\n", v->items[i]);
    printf("};\nconst size_t %s_n = %zu;\n\n", name, v->len);
}

int main(int argc, char **argv) {
    if (argc != 2) { fputs("usage: gen_psl <list.dat>\n", stderr); return 2; }
    FILE *f = fopen(argv[1], "r");
    if (f == NULL) { perror("fopen"); return 1; }

    vec rules = {0}, wildcards = {0}, exceptions = {0};
    char line[1024];
    while (fgets(line, sizeof line, f) != NULL) {
        /* trim trailing CR/LF and any whitespace */
        size_t n = strlen(line);
        while (n > 0 && (line[n - 1] == '\n' || line[n - 1] == '\r' ||
                         line[n - 1] == ' '  || line[n - 1] == '\t')) {
            line[--n] = '\0';
        }
        if (n == 0) continue;
        if (line[0] == '/' && line[1] == '/') continue; /* comment */

        char *rule = line;
        if (rule[0] == '!') {
            ascii_lower(rule + 1);
            vec_push(&exceptions, rule + 1);
        } else if (rule[0] == '*' && rule[1] == '.') {
            ascii_lower(rule + 2);
            vec_push(&wildcards, rule + 2); /* store the parent of the wildcard */
        } else {
            ascii_lower(rule);
            vec_push(&rules, rule);
        }
    }
    fclose(f);

    sort_unique(&rules);
    sort_unique(&wildcards);
    sort_unique(&exceptions);

    printf("/* Generated by tools/gen_psl from the vendored Public Suffix List.\n"
           " * Do not edit. Regenerate via the build (depends on the .dat). */\n");
    printf("#include \"psl_data.h\"\n\n");
    emit("psl_rules", &rules);
    emit("psl_wildcards", &wildcards);
    emit("psl_exceptions", &exceptions);
    return 0;
}
