/*
 * js_dom_ext -- DOM Standard surface beyond the core facade in js_dom: Node tree
 * navigation (getRootNode, isConnected, previous siblings), toggleAttribute,
 * compareDocumentPosition, attachShadow, TreeWalker / NodeIterator, importNode /
 * adoptNode, Range and elementFromPoint. Defined ONCE on the interface prototypes the
 * element wrappers inherit (HTMLElement -> Element -> Node), over the same sealed
 * `dom` natives: no new native capability, no network, nothing outside the page's
 * own document. Extracted as its own module (anti-monolith). See spec/js_dom.md 7g.
 */

#include "js_dom_ext.h"

static const char JDX_SHIM[] =
    "(function(){ var g=__G, d=g.document, EP=(g.Element&&g.Element.prototype)||null;"
    "  if(!d||!EP) return;"
    "  var W=g.__wrap;"
    /* element-only parent walk, bounded (a hostile DOM can be deep) */
    "  function rootOf(h){ var r=h, p=dom.parent(h), n=0;"
    "    while(p!==null&&n++<100000){ r=p; p=dom.parent(p); } return r; }"
    "  function isDocRoot(h){ var t=dom.tagName(h); return !!t&&String(t).toLowerCase()==='html'; }"
    "  Object.defineProperty(EP,'isConnected',{configurable:true,get:function(){ return isDocRoot(rootOf(this._h)); }});"
    "  EP.getRootNode=function(){ var r=rootOf(this._h); return isDocRoot(r)?d:W(r); };"
    "  function prevOf(h){ var p=dom.parent(h); if(p===null) return null;"
    "    var c=dom.firstChild(p), prev=null, n=0;"
    "    while(c!==null&&c!==h&&n++<100000){ prev=c; c=dom.nextSibling(c); }"
    "    return (c===h)?prev:null; }"
    "  Object.defineProperty(EP,'previousElementSibling',{configurable:true,get:function(){ var p=prevOf(this._h); return p===null?null:W(p); }});"
    "  Object.defineProperty(EP,'previousSibling',{configurable:true,get:function(){ var p=dom.siblingNode(this._h,true); return p===null?null:W(p); }});"
    /* Text / Comment wrappers (spec/js_dom.md 7h): CharacterData over a real node
     * handle, so insertion, removal, identity and rendering are the element ones. */
    "  var TP=(g.Text&&g.Text.prototype)||null, CP=(g.Comment&&g.Comment.prototype)||null;"
    "  function cdata(h){ var v=dom.textContent(h); return v==null?'':String(v); }"
    "  g.__wrapChar=function(h,k){ var o=Object.create(k===3?(TP||Object.prototype):(CP||Object.prototype));"
    "    var C={_h:h, nodeType:k, nodeName:k===3?'#text':'#comment', TEXT_NODE:3, COMMENT_NODE:8, ELEMENT_NODE:1,"
    "      get data(){ return cdata(h); }, set data(v){ dom.setText(h,String(v)); },"
    "      get nodeValue(){ return cdata(h); }, set nodeValue(v){ dom.setText(h,String(v==null?'':v)); },"
    "      get textContent(){ return cdata(h); }, set textContent(v){ dom.setText(h,String(v==null?'':v)); },"
    "      get wholeText(){ return cdata(h); }, get length(){ return cdata(h).length; },"
    "      get ownerDocument(){ return d; },"
    "      get parentNode(){ var p=dom.parent(h); return p===null?null:W(p); },"
    "      get parentElement(){ var p=dom.parent(h); return p===null?null:W(p); },"
    "      get nextSibling(){ var x=dom.siblingNode(h,false); return x===null?null:W(x); },"
    "      get previousSibling(){ var x=dom.siblingNode(h,true); return x===null?null:W(x); },"
    "      get nextElementSibling(){ var x=dom.siblingNode(h,false), n=0;"
    "        while(x!==null&&dom.nodeKind(x)!==1&&n++<100000) x=dom.siblingNode(x,false); return x===null?null:W(x); },"
    "      get previousElementSibling(){ var x=dom.siblingNode(h,true), n=0;"
    "        while(x!==null&&dom.nodeKind(x)!==1&&n++<100000) x=dom.siblingNode(x,true); return x===null?null:W(x); },"
    "      firstChild:null, lastChild:null, childNodes:[],"
    "      hasChildNodes:function(){ return false; }, contains:function(o){ return o===this; },"
    "      appendData:function(t){ this.data=this.data+String(t); },"
    "      insertData:function(i,t){ var x=this.data; i=Math.max(0,Math.min(i|0,x.length)); this.data=x.slice(0,i)+String(t)+x.slice(i); },"
    "      deleteData:function(i,c){ var x=this.data; i=i|0; this.data=x.slice(0,i)+x.slice(i+(c|0)); },"
    "      replaceData:function(i,c,t){ var x=this.data; i=i|0; this.data=x.slice(0,i)+String(t)+x.slice(i+(c|0)); },"
    "      substringData:function(i,c){ return this.data.substr(i|0,c|0); },"
    "      splitText:function(off){ var x=this.data; off=off|0; if(off<0||off>x.length){"
    "          var e=new Error('Index or size is negative or greater than the allowed amount'); e.name='IndexSizeError'; throw e; }"
    "        var t=d.createTextNode(x.slice(off)); this.data=x.slice(0,off); var p=dom.parent(h);"
    "        if(p!==null) dom.insertBefore(p,t._h,dom.siblingNode(h,false)); return t; },"
    "      remove:function(){ var p=dom.parent(h); if(p!==null) dom.removeChild(p,h); },"
    "      before:function(){ var p=dom.parent(h); if(p===null) return; var e=W(p);"
    "        for(var i=0;i<arguments.length;i++) e.insertBefore(typeof arguments[i]==='string'?d.createTextNode(arguments[i]):arguments[i], this); },"
    "      after:function(){ var p=dom.parent(h); if(p===null) return; var e=W(p), nx=this.nextSibling;"
    "        for(var i=0;i<arguments.length;i++) e.insertBefore(typeof arguments[i]==='string'?d.createTextNode(arguments[i]):arguments[i], nx); },"
    "      replaceWith:function(){ var p=dom.parent(h); if(p===null) return; var nx=this.nextSibling; var e=W(p);"
    "        dom.removeChild(p,h); for(var i=0;i<arguments.length;i++)"
    "          e.insertBefore(typeof arguments[i]==='string'?d.createTextNode(arguments[i]):arguments[i], nx); },"
    "      cloneNode:function(){ var c=dom.cloneNode(h,false); return c===null?null:W(c); },"
    "      addEventListener:function(t,fn,o){ g.__evAdd('n'+h,t,fn,o); },"
    "      removeEventListener:function(t,fn,o){ g.__evRemove('n'+h,t,fn,o); },"
    "      dispatchEvent:function(ev){ return g.__evDispatch('n'+h,ev); } };"
    "    Object.getOwnPropertyNames(C).forEach(function(n){"
    "      Object.defineProperty(o,n,Object.getOwnPropertyDescriptor(C,n)); });"
    "    return o; };"
    "  EP.toggleAttribute=function(n,force){ n=String(n); var has=this.hasAttribute(n);"
    "    var want=(force===undefined)?!has:!!force;"
    "    if(want&&!has) this.setAttribute(n,''); else if(!want&&has) this.removeAttribute(n);"
    "    return want; };"
    /* compareDocumentPosition: real tree order (ids do not follow later insertions) */
    "  function chain(h){ var a=[h], p=dom.parent(h), n=0;"
    "    while(p!==null&&n++<100000){ a.push(p); p=dom.parent(p); } return a.reverse(); }"
    "  var NPp=(g.Node&&g.Node.prototype)||null;"
    "  EP.compareDocumentPosition=function(o){ if(!o||o._h===undefined) return 1|32;"
    "    var a=this._h, b=o._h; if(a===b) return 0;"
    "    var ca=chain(a), cb=chain(b); if(ca[0]!==cb[0]) return 1|32|(a<b?4:2);"
    "    var i=0; while(i<ca.length&&i<cb.length&&ca[i]===cb[i]) i++;"
    "    if(i===ca.length) return 16|4;"
    "    if(i===cb.length) return 8|2;"
    "    var x=ca[i], y=cb[i], c=dom.childNode(ca[i-1],false), n=0;"
    "    while(c!==null&&n++<100000){ if(c===x) return 4; if(c===y) return 2; c=dom.siblingNode(c,false); }"
    "    return 1|32; };"
    /* the tree-position members apply to every node, text included */
    "  if(NPp&&NPp!==EP){ NPp.compareDocumentPosition=EP.compareDocumentPosition;"
    "    NPp.getRootNode=EP.getRootNode;"
    "    Object.defineProperty(NPp,'isConnected',Object.getOwnPropertyDescriptor(EP,'isConnected')); }"
    /* attachShadow visible v1 (spec/js_dom.md 7k): the fragment stays the
     * identity (host/shadowRoot/mode preserved) but every mutation ALSO mirrors
     * into the host's light DOM via dom.*, so the next pv_build_styled paints it.
     * innerHTML/textContent append (never replace light); <slot> stays empty and
     * transparent, so light shows in place plus shadow chrome after it. */
    "  var SH={};"
    "  EP.attachShadow=function(init){ var h=this._h;"
    "    if(SH[h]){ var e=new Error('Shadow root cannot be created on a host which already hosts one');"
    "      e.name='NotSupportedError'; throw e; }"
    "    var sr=d.createDocumentFragment(); sr.host=this; sr.mode=(init&&init.mode==='closed')?'closed':'open';"
    "    function mirAdd(ch){ try{ if(ch&&ch._h!==undefined) dom.appendChild(h,ch._h); }catch(x){} }"
    "    function mirIns(ch,ref){ try{ if(ch&&ch._h!==undefined)"
    "      dom.insertBefore(h,ch._h,(ref&&ref._h!==undefined)?ref._h:null); }catch(x){} }"
    "    function mirRm(ch){ try{ if(ch&&ch._h!==undefined) dom.removeChild(h,ch._h); }catch(x){} }"
    "    var _ap=sr.appendChild.bind(sr);"
    "    sr.appendChild=function(c){ var r=_ap(c); mirAdd(c); return r; };"
    "    var _ib=sr.insertBefore.bind(sr);"
    "    sr.insertBefore=function(n,ref){ var r=_ib(n,ref); mirIns(n,ref); return r; };"
    "    var _rm=sr.removeChild.bind(sr);"
    "    sr.removeChild=function(c){ var r=_rm(c); mirRm(c); return r; };"
    "    var _app=sr.append.bind(sr);"
    "    sr.append=function(){ var a=arguments,r=_app.apply(sr,a);"
    "      for(var i=0;i<a.length;i++){ var n=a[i];"
    "        if(typeof n==='string'){ var t=d.createTextNode(n); try{ _ap(t); }catch(x){} mirAdd(t); }"
    "        else mirAdd(n); } return r; };"
    "    var _pre=sr.prepend.bind(sr);"
    "    sr.prepend=function(){ var a=arguments,r=_pre.apply(sr,a);"
    "      for(var i=0;i<a.length;i++){ var n=a[i];"
    "        if(typeof n==='string'){ var t=d.createTextNode(n); try{ _ap(t); }catch(x){} mirAdd(t); }"
    "        else mirAdd(n); } return r; };"
    "    Object.defineProperty(sr,'innerHTML',{configurable:true,"
    "      get:function(){ return ''; },"
    "      set:function(html){ try{ var kids=sr.childNodes.slice();"
    "          for(var i=0;i<kids.length;i++) try{ sr.removeChild(kids[i]); }catch(x){} }catch(x){}"
    "        var t=d.createElement('div'); t.innerHTML=String(html); var c,m=0;"
    "        while((c=t.firstElementChild)!==null&&m++<100000){ t.removeChild(c); sr.appendChild(c); }"
    "        try{ var tx=t.textContent; if(tx) sr.appendChild(d.createTextNode(tx)); }catch(x){} } });"
    "    sr.replaceChildren=function(){ try{ var kids=sr.childNodes.slice();"
    "        for(var i=0;i<kids.length;i++) try{ sr.removeChild(kids[i]); }catch(x){} }catch(x){}"
    "      for(var j=0;j<arguments.length;j++){ var n=arguments[j];"
    "        if(typeof n==='string') sr.appendChild(d.createTextNode(n)); else sr.appendChild(n); } };"
    "    Object.defineProperty(sr,'textContent',{configurable:true,"
    "      get:function(){ return ''; },"
    "      set:function(v){ try{ var kids=sr.childNodes.slice();"
    "          for(var i=0;i<kids.length;i++) try{ sr.removeChild(kids[i]); }catch(x){} }catch(x){}"
    "        if(v) sr.appendChild(d.createTextNode(String(v))); } });"
    "    sr.innerHTML=''; SH[h]=sr; return sr; };"
    "  Object.defineProperty(EP,'shadowRoot',{configurable:true,get:function(){"
    "    var sr=SH[this._h]; return (sr&&sr.mode==='open')?sr:null; }});"
    /* TreeWalker / NodeIterator over ELEMENTS (text nodes are not represented);
     * every traversal ends in null, so a page loop always terminates. */
    "  var NF={SHOW_ALL:0xFFFFFFFF,SHOW_ELEMENT:1,SHOW_TEXT:4,SHOW_COMMENT:128,"
    "    FILTER_ACCEPT:1,FILTER_REJECT:2,FILTER_SKIP:3};"
    "  g.NodeFilter=NF;"
    "  function accept(f,w){ if(!f) return 1; var r=(typeof f==='function')?f(w):f.acceptNode(w);"
    "    return Number(r)||1; }"
    "  function nextIn(h,root,skipKids){ if(!skipKids&&dom.nodeKind(h)===1){ var c=dom.childNode(h,false); if(c!==null) return c; }"
    "    var n=0; while(h!==root&&n++<100000){ var s=dom.siblingNode(h,false); if(s!==null) return s;"
    "      h=dom.parent(h); if(h===null) return null; } return null; }"
    /* whatToShow bit of a node: 1 << (nodeType - 1) (DOM 6.1) */
    "  function shown(what,h){ if(what===undefined) return true; var k=dom.nodeKind(h);"
    "    return k>0&&(((what>>>0)>>>(k-1))&1)!==0; }"
    "  d.createTreeWalker=function(root,what,filter){ var r=root&&root._h!==undefined?root._h:null;"
    "    var cur=r, guard=0;"
    "    return { root:root, whatToShow:what, filter:filter||null,"
    "      get currentNode(){ return cur===null?null:W(cur); },"
    "      set currentNode(v){ if(v&&v._h!==undefined) cur=v._h; },"
    "      nextNode:function(){ if(cur===null) return null; var n=cur;"
    "        while(guard++<1000000){ n=nextIn(n,r,false); if(n===null) return null;"
    "          if(!shown(what,n)) continue;"
    "          var v=accept(filter,W(n)); if(v===1){ cur=n; return W(n); } }"
    "        return null; },"
    "      parentNode:function(){ if(cur===null||cur===r) return null; var p=dom.parent(cur);"
    "        if(p===null) return null; cur=p; return W(p); },"
    "      firstChild:function(){ var c=cur===null?null:dom.childNode(cur,false); while(c!==null&&!shown(what,c)) c=dom.siblingNode(c,false);"
    "        if(c===null) return null; cur=c; return W(c); },"
    "      nextSibling:function(){ var s=cur===null?null:dom.siblingNode(cur,false); while(s!==null&&!shown(what,s)) s=dom.siblingNode(s,false);"
    "        if(s===null) return null; cur=s; return W(s); },"
    "      previousNode:function(){ return null; }, lastChild:function(){ return null; },"
    "      previousSibling:function(){ return null; } }; };"
    "  d.createNodeIterator=function(root,what,filter){ var r=root&&root._h!==undefined?root._h:null;"
    "    var next=r, guard=0;"
    "    return { root:root, whatToShow:what, filter:filter||null, referenceNode:root,"
    "      nextNode:function(){"
    "        while(next!==null&&guard++<1000000){ var n=next; next=nextIn(n,r,false);"
    "          if(shown(what,n)&&accept(filter,W(n))===1) return W(n); }"
    "        return null; },"
    "      previousNode:function(){ return null; }, detach:function(){} }; };"
    "  d.importNode=function(n,deep){ return (n&&typeof n.cloneNode==='function')?n.cloneNode(!!deep):n; };"
    "  d.adoptNode=function(n){ return n; };"
    /* Range: enough for createContextualFragment and the measuring calls */
    "  d.createRange=function(){ var start=null;"
    "    function rect(){ return {x:0,y:0,top:0,left:0,right:0,bottom:0,width:0,height:0}; }"
    "    return { collapsed:true, startOffset:0, endOffset:0,"
    "      get startContainer(){ return start; }, get endContainer(){ return start; },"
    "      selectNode:function(n){ start=n; }, selectNodeContents:function(n){ start=n; },"
    "      setStart:function(n){ start=n; }, setEnd:function(){}, collapse:function(){},"
    "      setStartBefore:function(n){ start=n; }, setStartAfter:function(n){ start=n; },"
    "      setEndBefore:function(){}, setEndAfter:function(){}, detach:function(){},"
    "      cloneRange:function(){ return d.createRange(); }, toString:function(){ return ''; },"
    "      deleteContents:function(){}, insertNode:function(){},"
    "      getBoundingClientRect:rect, getClientRects:function(){ return []; },"
    "      createContextualFragment:function(html){ var t=d.createElement('div');"
    "        t.innerHTML=String(html); var f=d.createDocumentFragment(), c, n=0;"
    "        while((c=t.firstElementChild)!==null&&n++<100000){ t.removeChild(c); f.appendChild(c); }"
    "        return f; } }; };"
    /* insertAdjacent*: content is parsed/placed in a scratch element, then every node of
     * it (text included) moves to the position by the native dom.moveChildren. */
    "  function adjPlace(el,pos){ var h=el._h; pos=String(pos).toLowerCase();"
    "    if(pos==='beforeend') return [h,0,null]; if(pos==='afterbegin') return [h,1,null];"
    "    var p=dom.parent(h); if(p===null) return null;"
    "    if(pos==='beforebegin') return [p,2,h]; if(pos==='afterend') return [p,3,h];"
    "    var e=new Error('Invalid position'); e.name='SyntaxError'; throw e; }"
    "  function adjMove(el,pos,fill){ var where=adjPlace(el,pos);   /* bad position: SyntaxError */"
    "    if(where===null) return null; var t=d.createElement('div'); fill(t);"
    "    return dom.moveChildren(t._h, where[0], where[1], where[2]); }"
    "  EP.insertAdjacentElement=function(pos,node){ if(!node||node._h===undefined) return null;"
    "    return adjMove(this,pos,function(t){ t.appendChild(node); })?node:null; };"
    "  EP.insertAdjacentHTML=function(pos,html){ adjMove(this,pos,function(t){ t.innerHTML=String(html); }); };"
    "  EP.insertAdjacentText=function(pos,txt){ adjMove(this,pos,function(t){ t.textContent=String(txt); }); };"
    /* Real methods/accessors on the interface prototypes, delegating to the wrapper's
     * own members: what Shadow DOM / instrumentation polyfills capture and re-call
     * (youtube's webcomponents-sd stored Node.prototype.* and got undefined). */
    "  function ownD(o,n){ return o!=null?Object.getOwnPropertyDescriptor(o,n):undefined; }"
    "  function delegM(P,names){ if(!P) return; names.forEach(function(n){"
    "    if(Object.prototype.hasOwnProperty.call(P,n)) return;"
    "    Object.defineProperty(P,n,{configurable:true,writable:true,value:function(){"
    "      var dd=ownD(this,n); if(dd&&typeof dd.value==='function') return dd.value.apply(this,arguments);"
    "      throw new TypeError('Illegal invocation'); }}); }); }"
    "  function delegA(P,names){ if(!P) return; names.forEach(function(n){"
    "    if(Object.prototype.hasOwnProperty.call(P,n)) return;"
    "    Object.defineProperty(P,n,{configurable:true,"
    "      get:function(){ var dd=ownD(this,n); return dd?(dd.get?dd.get.call(this):dd.value):undefined; },"
    "      set:function(v){ var dd=ownD(this,n); if(dd&&dd.set) dd.set.call(this,v);"
    "        else if(dd&&dd.writable) dd.value=v; }}); }); }"
    "  delegM(g.EventTarget&&g.EventTarget.prototype,['addEventListener','removeEventListener','dispatchEvent']);"
    "  delegM(g.Node&&g.Node.prototype,['appendChild','insertBefore','removeChild','replaceChild','cloneNode',"
    "    'contains','hasChildNodes']);"
    "  delegA(g.Node&&g.Node.prototype,['textContent','parentNode','parentElement','childNodes','firstChild',"
    "    'lastChild','nextSibling','ownerDocument','nodeName','nodeType']);"
    "  delegM(EP,['setAttribute','getAttribute','removeAttribute','hasAttribute','getAttributeNames',"
    "    'querySelector','querySelectorAll','getElementsByTagName','getElementsByClassName','matches','closest',"
    "    'append','prepend','before','after','replaceWith','replaceChildren','remove','getBoundingClientRect',"
    "    'getClientRects','scrollIntoView']);"
    "  delegA(EP,['innerHTML','className','id','children','firstElementChild','lastElementChild',"
    "    'nextElementSibling','classList','tagName','attributes','childElementCount']);"
    "  var HP=g.HTMLElement&&g.HTMLElement.prototype;"
    "  delegM(HP,['click','focus','blur']); delegA(HP,['innerText','style','dataset','hidden','title']);"
    /* isEqualNode: bounded by the subtree walk (each node compared once). */
    "  function eqNode(a,b){ if(a===b) return true; if(!a||!b||a.nodeType!==b.nodeType) return false;"
    "    if(a.nodeType!==1) return String(a.nodeValue==null?a.data:a.nodeValue)===String(b.nodeValue==null?b.data:b.nodeValue);"
    "    if(String(a.tagName)!==String(b.tagName)) return false;"
    "    var na=a.getAttributeNames(), nb=b.getAttributeNames(); if(na.length!==nb.length) return false;"
    "    for(var i=0;i<na.length;i++){ if(!b.hasAttribute(na[i])||b.getAttribute(na[i])!==a.getAttribute(na[i])) return false; }"
    "    if(String(a.textContent)!==String(b.textContent)) return false;"
    "    var ca=a.childNodes, cb=b.childNodes; if(ca.length!==cb.length) return false;"
    "    for(var j=0;j<ca.length;j++) if(!eqNode(ca[j],cb[j])) return false;"
    "    return true; }"
    "  [g.Node&&g.Node.prototype, EP].forEach(function(P){ if(!P) return;"
    "    P.isEqualNode=function(o){ return eqNode(this,o); }; P.isSameNode=function(o){ return this===o; }; });"
    "  if(typeof d.elementFromPoint!=='function') d.elementFromPoint=function(){ return null; };"
    "  if(typeof d.elementsFromPoint!=='function') d.elementsFromPoint=function(){ return []; };"
    "})()";

/* Binary data and in-page messaging: Blob/File/FileReader, object URLs,
 * structuredClone, MessageChannel, BroadcastChannel. Nothing here reaches the
 * network or another window: object URLs are opaque names (no fetch of blob: yet),
 * channels deliver within this page's own realm, asynchronously like a browser. */
static const char JDX_DATA_SHIM[] =
    "(function(){ var g=__G;"
    "  function u8(s){ s=String(s); var o=[];"
    "    for(var i=0;i<s.length;i++){ var c=s.charCodeAt(i);"
    "      if(c>=0xD800&&c<=0xDBFF&&i+1<s.length){ var d=s.charCodeAt(i+1);"
    "        if(d>=0xDC00&&d<=0xDFFF){ c=0x10000+((c-0xD800)<<10)+(d-0xDC00); i++; } }"
    "      if(c<0x80) o.push(c); else if(c<0x800) o.push(0xC0|c>>6,0x80|c&63);"
    "      else if(c<0x10000) o.push(0xE0|c>>12,0x80|c>>6&63,0x80|c&63);"
    "      else o.push(0xF0|c>>18,0x80|c>>12&63,0x80|c>>6&63,0x80|c&63); }"
    "    return new Uint8Array(o); }"
    "  function fromU8(b){ var s='', i=0;"
    "    while(i<b.length){ var c=b[i++];"
    "      if(c>=0xF0&&i+2<b.length+0){ c=((c&7)<<18)|((b[i++]&63)<<12)|((b[i++]&63)<<6)|(b[i++]&63); c-=0x10000;"
    "        s+=String.fromCharCode(0xD800+(c>>10),0xDC00+(c&1023)); continue; }"
    "      if(c>=0xE0) c=((c&15)<<12)|((b[i++]&63)<<6)|(b[i++]&63);"
    "      else if(c>=0xC0) c=((c&31)<<6)|(b[i++]&63);"
    "      s+=String.fromCharCode(c); } return s; }"
    "  function bytesOf(p){ if(p instanceof Blob) return p._b;"
    "    if(p instanceof ArrayBuffer) return new Uint8Array(p);"
    "    if(p&&ArrayBuffer.isView(p)) return new Uint8Array(p.buffer,p.byteOffset,p.byteLength);"
    "    return u8(p); }"
    "  function Blob(parts,opt){ var chunks=(parts||[]).map(bytesOf), n=0;"
    "    chunks.forEach(function(c){ n+=c.length; }); var b=new Uint8Array(n), o=0;"
    "    chunks.forEach(function(c){ b.set(c,o); o+=c.length; });"
    "    this._b=b; this.size=n; this.type=(opt&&opt.type)?String(opt.type).toLowerCase():''; }"
    "  Blob.prototype.text=function(){ return Promise.resolve(fromU8(this._b)); };"
    "  Blob.prototype.arrayBuffer=function(){ return Promise.resolve(this._b.slice().buffer); };"
    "  Blob.prototype.bytes=function(){ return Promise.resolve(this._b.slice()); };"
    "  Blob.prototype.slice=function(a,e,t){ var n=this.size; a=a===undefined?0:a|0; e=e===undefined?n:e|0;"
    "    if(a<0) a=Math.max(n+a,0); if(e<0) e=Math.max(n+e,0); a=Math.min(a,n); e=Math.min(Math.max(e,a),n);"
    "    var r=new Blob([],{type:t||''}); r._b=this._b.slice(a,e); r.size=r._b.length; return r; };"
    "  Blob.prototype.stream=function(){ var self=this, done=false; return { getReader:function(){ return {"
    "    read:function(){ if(done) return Promise.resolve({done:true,value:undefined}); done=true;"
    "      return Promise.resolve({done:false,value:self._b.slice()}); }, releaseLock:function(){},"
    "    cancel:function(){ return Promise.resolve(); } }; } }; };"
    "  function File(parts,name,opt){ Blob.call(this,parts,opt); this.name=String(name);"
    "    this.lastModified=0; this.webkitRelativePath=''; }"
    "  File.prototype=Object.create(Blob.prototype); File.prototype.constructor=File;"
    "  g.Blob=Blob; g.File=File;"
    "  function FileReader(){ this.readyState=0; this.result=null; this.error=null; this._l={}; }"
    "  FileReader.EMPTY=0; FileReader.LOADING=1; FileReader.DONE=2;"
    "  FileReader.prototype.addEventListener=function(t,f){ (this._l[t]=this._l[t]||[]).push(f); };"
    "  FileReader.prototype.removeEventListener=function(t,f){ var a=this._l[t]; if(a){ var i=a.indexOf(f); if(i>=0) a.splice(i,1); } };"
    "  function finish(fr,val){ fr.readyState=1; g.setTimeout(function(){ fr.readyState=2; fr.result=val;"
    "    var ev={type:'load',target:fr};"
    "    ['load','loadend'].forEach(function(t){ ev.type=t; if(typeof fr['on'+t]==='function') fr['on'+t](ev);"
    "      (fr._l[t]||[]).forEach(function(f){ f.call(fr,ev); }); }); },0); }"
    "  FileReader.prototype.readAsText=function(b){ finish(this, fromU8(bytesOf(b))); };"
    "  FileReader.prototype.readAsArrayBuffer=function(b){ finish(this, bytesOf(b).slice().buffer); };"
    "  FileReader.prototype.readAsBinaryString=function(b){ var x=bytesOf(b), s='';"
    "    for(var i=0;i<x.length;i++) s+=String.fromCharCode(x[i]); finish(this,s); };"
    "  FileReader.prototype.readAsDataURL=function(b){ var x=bytesOf(b), s='';"
    "    for(var i=0;i<x.length;i++) s+=String.fromCharCode(x[i]);"
    "    var t=(b&&b.type)||'application/octet-stream';"
    "    finish(this, 'data:'+t+';base64,'+(typeof g.btoa==='function'?g.btoa(s):'')); };"
    "  FileReader.prototype.abort=function(){ this.readyState=2; };"
    "  g.FileReader=FileReader;"
    "  var objUrls={}, seq=0;"
    "  if(g.URL){ g.URL.createObjectURL=function(b){ var u='blob:'+((g.location&&g.location.origin)||'null')+'/'+(++seq);"
    "      objUrls[u]=b; return u; };"
    "    g.URL.revokeObjectURL=function(u){ delete objUrls[u]; }; }"
    "  g.__objectUrl=function(u){ return objUrls[u]||null; };"
    /* structuredClone: HTML's serialisable subset, cycles preserved; a function or a
     * symbol is a DataCloneError like in a browser. */
    "  function dcErr(){ var e=new Error('The object could not be cloned.'); e.name='DataCloneError'; return e; }"
    "  function clone(v,seen){ if(v===null||typeof v!=='object'){"
    "      if(typeof v==='function'||typeof v==='symbol') throw dcErr(); return v; }"
    "    if(seen.has(v)) return seen.get(v); var r;"
    "    if(v instanceof Date) r=new Date(v.getTime());"
    "    else if(v instanceof RegExp) r=new RegExp(v.source,v.flags);"
    "    else if(v instanceof ArrayBuffer) r=v.slice(0);"
    "    else if(ArrayBuffer.isView(v)) r=new v.constructor(v);"
    "    else if(v instanceof Blob){ r=v.slice(0,v.size,v.type); if(v instanceof File){ r=new File([v._b],v.name,{type:v.type}); } }"
    "    else if(v instanceof Map){ r=new Map(); seen.set(v,r); v.forEach(function(x,k){ r.set(clone(k,seen),clone(x,seen)); }); return r; }"
    "    else if(v instanceof Set){ r=new Set(); seen.set(v,r); v.forEach(function(x){ r.add(clone(x,seen)); }); return r; }"
    "    else if(Array.isArray(v)){ r=[]; seen.set(v,r); for(var i=0;i<v.length;i++) r[i]=clone(v[i],seen); return r; }"
    "    else if(v instanceof Error){ r=new Error(v.message); r.name=v.name; }"
    "    else { r={}; seen.set(v,r); Object.keys(v).forEach(function(k){ r[k]=clone(v[k],seen); }); return r; }"
    "    seen.set(v,r); return r; }"
    "  g.structuredClone=function(v){ return clone(v,new Map()); };"
    /* MessageChannel / BroadcastChannel: in-page, async, cloned payloads. */
    "  function Port(){ this.onmessage=null; this._other=null; this._l=[]; this._closed=false; }"
    "  Port.prototype.postMessage=function(d){ var o=this._other; if(!o||this._closed||o._closed) return;"
    "    var data=g.structuredClone(d);"
    "    g.setTimeout(function(){ var ev={type:'message',data:data,ports:[],origin:''};"
    "      if(typeof o.onmessage==='function') o.onmessage(ev); o._l.forEach(function(f){ f.call(o,ev); }); },0); };"
    "  Port.prototype.addEventListener=function(t,f){ if(t==='message'&&typeof f==='function') this._l.push(f); };"
    "  Port.prototype.removeEventListener=function(t,f){ var i=this._l.indexOf(f); if(i>=0) this._l.splice(i,1); };"
    "  Port.prototype.start=function(){}; Port.prototype.close=function(){ this._closed=true; };"
    "  g.MessagePort=Port;"
    "  g.MessageChannel=function(){ this.port1=new Port(); this.port2=new Port();"
    "    this.port1._other=this.port2; this.port2._other=this.port1; };"
    "  var bc={};"
    "  g.BroadcastChannel=function(name){ this.name=String(name); this.onmessage=null; this._closed=false;"
    "    (bc[this.name]=bc[this.name]||[]).push(this); };"
    "  g.BroadcastChannel.prototype.postMessage=function(d){ var self=this, data=g.structuredClone(d);"
    "    (bc[this.name]||[]).forEach(function(c){ if(c!==self&&!c._closed) g.setTimeout(function(){"
    "      if(typeof c.onmessage==='function') c.onmessage({type:'message',data:data}); },0); }); };"
    "  g.BroadcastChannel.prototype.close=function(){ this._closed=true; };"
    "  g.BroadcastChannel.prototype.addEventListener=function(t,f){ if(t==='message') this.onmessage=f; };"
    "  g.BroadcastChannel.prototype.removeEventListener=function(){};"
    "})()";

static int run(JSContext *ctx, const char *src, size_t len, const char *name) {
    JSValue r = JS_Eval(ctx, src, len, name, JS_EVAL_TYPE_GLOBAL);
    int ok = !JS_IsException(r);
    if (!ok) JS_FreeValue(ctx, JS_GetException(ctx));
    JS_FreeValue(ctx, r);
    return ok ? 0 : -1;
}

int jdx_install(JSContext *ctx) {
    if (run(ctx, JDX_SHIM, sizeof JDX_SHIM - 1, "<dom-ext>") != 0) return -1;
    return run(ctx, JDX_DATA_SHIM, sizeof JDX_DATA_SHIM - 1, "<data-ext>");
}
